[package]
name = "silentsparrow"
version = "0.1.0"
edition = "2024"

[dependencies]
ed25519-dalek = { version = "2.1.1", features = ["rand_core"] }
rand_core = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version - "0.4", features = ["clock"] }
sha2 = "0.10"
hex = "0.4"
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }
tokio = { version = "1.0", features = ["full"] }
base64ct = "1.6"
directories = "5.0"
